baseURL = "http://study.impl.dev/"
languageCode = "en-us"
title = "Aimee's Study Notes"
theme = "hugo-bare-min-theme"

[Params]
  description = "Aimee's Study Notes"

[module]
  [[module.imports]]
    disabled = true

[Params.source]
url = "https://Aimeedeer/org-notes"   # Needed if you want to see .GitInfo for a page
md_dir = "content"                   # Needed if you want to get a link to Markdown source for each page
org_dir = ""      