baseURL = "http://study.impl.dev/"
languageCode = "en-us"
title = "Aimee's Study Notes"
theme = "hugo-bare-min-theme"

[Params]
  description = "Aimee's Study Notes"

[module]
  [[module.imports]]
    disabled = true